# Generated by Django 5.0.12 on 2025-06-15 11:48

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='application_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Application',
                'verbose_name_plural': 'Product Applications',
            },
        ),
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carousel_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Carousel Image',
                'verbose_name_plural': 'Product Carousel Images',
            },
        ),
        migrations.CreateModel(
            name='SingleProduct',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=2555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ManyToManyField(blank=True, null=True, related_name='single_products', to='product.application')),
                ('image', models.ManyToManyField(related_name='single_products', to='product.carouselimage')),
            ],
            options={
                'verbose_name': 'Single Product',
                'verbose_name_plural': 'Single Products',
            },
        ),
        migrations.CreateModel(
            name='SingleProductSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('single_products', models.ManyToManyField(blank=True, null=True, related_name='single_product_sections', to='product.singleproduct')),
            ],
            options={
                'verbose_name': 'Single Product Section',
                'verbose_name_plural': 'Single Product Sections',
            },
        ),
    ]
