# Generated by Django 5.0.12 on 2025-06-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='title',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
