# Generated by Django 5.0.12 on 2025-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_carouselimage_options_carouselimage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='singleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carousel_images/'),
        ),
    ]
