# Generated by Django 5.0.12 on 2025-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_singleproduct_image_singleproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='single_product/'),
        ),
    ]
