# Generated by Django 5.0.12 on 2025-06-25 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=2555, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=2555, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('machine', models.CharField(blank=True, max_length=2555, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Form',
            },
        ),
    ]
