# Generated by Django 5.0.12 on 2025-06-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='machine',
            new_name='city',
        ),
    ]
