# Generated by Django 5.0.12 on 2025-06-15 14:05

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=2555)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='authors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(max_length=2555)),
                ('min_read', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(max_length=2555)),
                ('slug', models.SlugField(blank=True, max_length=2555, unique=True)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('content', ckeditor.fields.RichTextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.author')),
                ('related_blogs', models.ManyToManyField(blank=True, to='blog.blog')),
            ],
            options={
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
