# Generated by Django 5.0.12 on 2025-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_page/'),
        ),
    ]
