# Generated by Django 5.0.12 on 2025-06-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/'),
        ),
    ]
