# Generated by Django 5.0.12 on 2025-06-15 07:39

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_herosection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('testimonial_title', models.CharField(blank=True, max_length=2555, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about_images/')),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
