# Generated by Django 5.0.12 on 2025-06-15 08:09

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_aboutsection_alter_herosection_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSectionOfHowToStart',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sub Section of How To Start',
                'verbose_name_plural': 'Sub Sections of How To Start',
            },
        ),
        migrations.CreateModel(
            name='HowToStartSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='how_to_start_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_sections', models.ManyToManyField(blank=True, related_name='how_to_start_sections', to='homePage.subsectionofhowtostart')),
            ],
            options={
                'verbose_name': 'How To Start Section',
                'verbose_name_plural': 'How To Start Sections',
            },
        ),
    ]
