# Generated by Django 5.0.12 on 2025-06-15 10:36

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_subsectionofhowtostart_howtostartsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleProduction',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Single Production',
                'verbose_name_plural': 'Single Productions',
            },
        ),
        migrations.CreateModel(
            name='SingleProductionSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='production_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('single_production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='homePage.singleproduction')),
            ],
            options={
                'verbose_name': 'Single Production Section',
                'verbose_name_plural': 'Single Production Sections',
            },
        ),
        migrations.CreateModel(
            name='ProductionSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_sections', to='homePage.singleproductionsection')),
            ],
            options={
                'verbose_name': 'Production Section',
                'verbose_name_plural': 'Production Sections',
            },
        ),
    ]
