# Generated by Django 5.0.12 on 2025-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_singleproduction_singleproductionsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionsection',
            options={'verbose_name': 'Whole Production Section', 'verbose_name_plural': 'Whole Production Sections'},
        ),
        migrations.AlterModelOptions(
            name='singleproduction',
            options={'verbose_name': 'Product info', 'verbose_name_plural': 'Product infos'},
        ),
        migrations.AlterModelOptions(
            name='singleproductionsection',
            options={'verbose_name': 'Single Product info', 'verbose_name_plural': 'Single Product infos'},
        ),
        migrations.RemoveField(
            model_name='singleproductionsection',
            name='single_production',
        ),
        migrations.AddField(
            model_name='singleproductionsection',
            name='single_production',
            field=models.ManyToManyField(related_name='sections', to='homePage.singleproduction'),
        ),
    ]
