# Generated by Django 5.0.12 on 2025-06-15 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_singleproductionsection_section_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleproductionsection',
            name='section_title',
        ),
        migrations.CreateModel(
            name='ProductionSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('production', models.ManyToManyField(related_name='production_sections', to='homePage.singleproductionsection')),
            ],
            options={
                'verbose_name': 'Whole Production Section',
                'verbose_name_plural': 'Whole Production Sections',
            },
        ),
    ]
