# Generated by Django 5.0.12 on 2025-06-15 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_remove_singleproductionsection_section_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleproductionsection',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, max_length=2555, null=True),
        ),
    ]
