# Generated by Django 5.0.12 on 2025-06-25 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_alter_singleproductionsection_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(blank=True, max_length=2555, null=True)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Faq section',
                'verbose_name_plural': 'Faq sections',
            },
        ),
    ]
