# Generated by Django 5.0.12 on 2025-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutourstorysection',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutourstorysection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_story/'),
        ),
    ]
