# Generated by Django 5.0.12 on 2025-06-15 13:05

import ckeditor.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalResources',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='technical_resources_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Technical Resource',
                'verbose_name_plural': 'Technical Resources',
            },
        ),
        migrations.CreateModel(
            name='TechnicalResourceSection',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=2555, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('technical_resources', models.ManyToManyField(blank=True, null=True, related_name='technical_resource_sections', to='resources.technicalresources')),
            ],
            options={
                'verbose_name': 'Technical Resource Section',
                'verbose_name_plural': 'Technical Resource Sections',
            },
        ),
    ]
